# Generated by Django 6.0.7 on 2026-07-22 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام لیگ')),
                ('code', models.CharField(max_length=10, verbose_name='کد لیگ')),
                ('country', models.CharField(max_length=100, verbose_name='کشور صاحب لیگ')),
                ('logo_url', models.URLField(blank=True, verbose_name='آدرس لوگو')),
                ('api_id', models.IntegerField(unique=True, verbose_name='شناسه API')),
            ],
            options={
                'verbose_name': 'لیگ',
                'verbose_name_plural': 'لیگ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=40)),
                ('crest_url', models.URLField(blank=True)),
                ('api_id', models.IntegerField(unique=True, verbose_name='شناسه API')),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیم\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع لیگ')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان لیگ')),
                ('current_matchday', models.IntegerField(blank=True, null=True, verbose_name='هفته فعلی')),
                ('api_id', models.IntegerField(unique=True, verbose_name='شناسه API فصل')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='matches.league', verbose_name='لیگ مربوطه')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday', models.IntegerField(blank=True, null=True, verbose_name='هفته بازی')),
                ('starting_at', models.DateTimeField(verbose_name='زمان شروع بازی')),
                ('status', models.CharField(choices=[('SCHEDULED', 'برنامه\u200cریزی شده'), ('TIMED', 'زمان\u200cبندی شده'), ('IN_PLAY', 'در حال برگزاری'), ('PAUSED', 'بین دو نیمه'), ('EXTRA_TIME', 'وقت اضافه'), ('PENALTY_SHOOTOUT', 'ضربات پنالتی'), ('FINISHED', 'پایان یافته'), ('SUSPENDED', 'تعلیق شده'), ('POSTPONED', 'به تعویق افتاده'), ('CANCELLED', 'لغو شده'), ('AWARDED', 'رای کمیته انضباطی')], max_length=20, verbose_name='وضعیت بازی')),
                ('home_score', models.IntegerField(blank=True, null=True, verbose_name='گل میزبان')),
                ('away_score', models.IntegerField(blank=True, null=True, verbose_name='گل مهمان')),
                ('api_id', models.IntegerField(unique=True, verbose_name='شناسه API')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matches.league', verbose_name='لیگ\u200c')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_mathces', to='matches.season', verbose_name='فصل')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='matches.team', verbose_name='تیم مهمان')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='matches.team', verbose_name='تیم میزبان')),
            ],
            options={
                'verbose_name': 'بازی',
                'verbose_name_plural': 'بازی\u200cها',
            },
        ),
    ]
