# Generated by Django 6.0.7 on 2026-07-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='persian_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='persian_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
