# Generated by Django 6.0.7 on 2026-07-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_standing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standing',
            options={'ordering': ['position'], 'verbose_name': 'رده\u200cبندی تیم', 'verbose_name_plural': 'جدول\u200cهای رده\u200cبندی'},
        ),
    ]
